language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_retry composer update $COMPOSER_FLAGS --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --exclude-group=cron-task
  - wget https://scrutinizer-ci.com/ocular.phar

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
